version: '3'
services:
  get_stock:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./main.py:/usr/src/app/main.py
    environment:
      - SAVE_PATH=/data
      - TIME_TYPE=1
      - TOR_PASSWORD=tor
      - USE_TOR=True
      - TOR_REFRESH_TIME=3
      - TZ=Asia/Tokyo
    deploy:
      restart_policy:
        delay: 10s
        condition: on-failure
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://tor_proxy:9050
    command: python -B -u /usr/src/app/main.py
  tor_proxy:
    image: dperson/torproxy
    ports:
      - 8118:8118
      - 9050:9050
    environment:
      - PASSWORD=tor
      - TZ=Asia/Tokyo
